Models/Student.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace practice.Models;

public class Student
{
    public int Id { get; set; }

    [Required(ErrorMessage = "Фамилия обязательна")]
    [RegularExpression(@"^[А-ЯЁ][а-яё]*$", ErrorMessage = "Некорректная фамилия")]
    public string LastName { get; set; }

    [Required(ErrorMessage = "Имя обязательно")]
    [RegularExpression(@"^[А-ЯЁ][а-яё]*$", ErrorMessage = "Некорректное имя")]
    public string FirstName { get; set; }

    [RegularExpression(@"^[А-ЯЁ][а-яё]*$", ErrorMessage = "Некорректное отчество")]
    public string MiddleName { get; set; }

    [Required(ErrorMessage = "Фамилия на латинице обязательна")]
    [RegularExpression(@"^[A-Z][a-z]*$", ErrorMessage = "Некорректная фамилия на латинице")]
    public string LatinLastName { get; set; }

    [Required(ErrorMessage = "Имя на латинице обязательно")]
    [RegularExpression(@"^[A-Z][a-z]*$", ErrorMessage = "Некорректное имя на латинице")]
    public string LatinFirstName { get; set; }

    [RegularExpression(@"^[A-Z][a-z]*$", ErrorMessage = "Некорректное отчество на латинице")]
    public string LatinMiddleName { get; set; }

    [DataType(DataType.Date)]
    public DateTime DateOfBirth { get; set; }

    public string Gender { get; set; }

    [Required(ErrorMessage = "ИИН обязателен")]
    [RegularExpression(@"^\d{12}$", ErrorMessage = "ИИН должен содержать 12 цифр")]
    [CustomValidation(typeof(Student), "ValidateIIN")]
    public string IIN { get; set; }

    public string Citizenship { get; set; }

    public string Nationality { get; set; }

    public string Address { get; set; }

    [RegularExpression(@"\d{9}", ErrorMessage = "Неверный формат мобильного номера")]
    public string MobileNumber { get; set; }

    [EmailAddress(ErrorMessage = "Неверный формат Email")]
    public string Email { get; set; }

    [RegularExpression(@"\d{9}", ErrorMessage = "Неверный формат BIK кода")]
    public string BankBIK { get; set; }

    [RegularExpression(@"[A-Z]{2}\d{18}", ErrorMessage = "Неверный формат IBAN номера счета банка")]
    public string BankIBAN { get; set; }

    public static ValidationResult ValidateIIN(string iin, ValidationContext validationContext)
    {
        // Проверка на корректность ИИН согласно указанным требованиям
        int year = int.Parse(iin.Substring(0, 2));
        int month = int.Parse(iin.Substring(2, 2));
        int day = int.Parse(iin.Substring(4, 2));

        if (year < 0 || year > 99 || month < 1 || month > 12 || day < 1 || day > 31)
        {
            return new ValidationResult("Некорректная дата рождения в ИИН");
        }

        return ValidationResult.Success;
    }
}

Controllers/StudentController.cs
using System;
using Microsoft.AspNetCore.Mvc;
using practice.Models;
using System.Diagnostics;

public class StudentController : Controller
{
    private readonly ApplicationDbContext _context;

    public StudentController(ApplicationDbContext context)
    {
        _context = context;
    }

    public ActionResult Index()
    {
        return View();
    }

    [HttpPost]
    public ActionResult Register(Student student)
    {
        if (ModelState.IsValid)
        {
            // Добавить студента в базу данных
            _context.Students.Add(student);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }

        return View("Index", student);
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Index.cshtml
@model Student

@{
    ViewBag.Title = "Регистрация студента";
}

<h2>Регистрация студента</h2>

@using (Html.BeginForm("Register", "Student", FormMethod.Post))
{
    @Html.ValidationSummary(true)

    <div>
        @Html.LabelFor(model => model.LastName)
        @Html.TextBoxFor(model => model.LastName)
        @Html.ValidationMessageFor(model => model.LastName)
    </div>

    <div>
        @Html.LabelFor(model => model.FirstName)
        @Html.TextBoxFor(model => model.FirstName)
        @Html.ValidationMessageFor(model => model.FirstName)
    </div>

    <!-- Добавьте остальные поля модели -->

    <input type="submit" value="Зарегистрировать" />
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - practice</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/practice.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">practice</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - practice - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>